In [1]:
import pandas as pd

df = pd.read_csv('tip.csv')

df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
# 1.1
df.head(5)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
# 1.2
df.shape

(244, 7)

In [ ]:
# 1.3
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [ ]:
# 1.4
# df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 13.5 KB

In [ ]:
# 2.1
total_bill = df['total_bill']
total_bill

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [ ]:
# 2.2
total_amount = df[['total_bill', 'tip']]
total_amount

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [ ]:
# 2.3
df.head(10)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [ ]:
# 2.4
df.loc[5]

total_bill     25.29
tip             4.71
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 5, dtype: object

In [ ]:
# 3.1
all_filters = df[
    (df['total_bill'] > 20) & 
    (df['sex'] == 'Female') & 
    (df['time'] == 'Dinner') & 
    (df['total_bill'] + df['tip'] > 30)]

# 3.2
all_filters.shape

(8, 7)

In [ ]:
# 3.3
all_filters.head(5)

     total_bill   tip     sex smoker  day    time  size
11        35.26  5.00  Female     No  Sun  Dinner     4
52        34.81  5.20  Female     No  Sun  Dinner     4
73        25.28  5.00  Female    Yes  Sat  Dinner     2
102       44.30  2.50  Female    Yes  Sat  Dinner     3
155       29.85  5.14  Female     No  Sun  Dinner     5

In [25]:
# 4.1
mean_bill = df['total_bill'].mean()
# 4.2
max_tip = df['tip'].max()
# 4.3
df.isnull().sum()
# 4.4
df.time.value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [31]:
# 5.1
total_bill_mean = df.groupby('sex')['total_bill'].mean()
# 5.2
tip_mean = df.groupby('day')['tip'].mean()
# 5.3
visitors_per_day = df.groupby('day')['size'].sum()

In [32]:
visitors_per_day

day
Fri      40
Sat     219
Sun     216
Thur    152
Name: size, dtype: int64

In [ ]:
# 6.
df['tip_percentage'] = round(df['tip'] / df['total_bill']*100, 2)
df.head(10)

   total_bill   tip     sex smoker  day    time  size  tip_percentage
0       16.99  1.01  Female     No  Sun  Dinner     2            5.94
1       10.34  1.66    Male     No  Sun  Dinner     3           16.05
2       21.01  3.50    Male     No  Sun  Dinner     3           16.66
3       23.68  3.31    Male     No  Sun  Dinner     2           13.98
4       24.59  3.61  Female     No  Sun  Dinner     4           14.68
5       25.29  4.71    Male     No  Sun  Dinner     4           18.62
6        8.77  2.00    Male     No  Sun  Dinner     2           22.81
7       26.88  3.12    Male     No  Sun  Dinner     4           11.61
8       15.04  1.96    Male     No  Sun  Dinner     2           13.03
9       14.78  3.23    Male     No  Sun  Dinner     2           21.85

In [38]:
# 7
total_bill_order = df.sort_values('total_bill')
tip_order_desc = df.sort_values('tip', ascending=False)
top_5_tips = df.nlargest(5, 'tip')
top_5_tips

     total_bill    tip   sex smoker   day    time  size  tip_percentage
170       50.81  10.00  Male    Yes   Sat  Dinner     3           19.68
212       48.33   9.00  Male     No   Sat  Dinner     4           18.62
23        39.42   7.58  Male     No   Sat  Dinner     4           19.23
59        48.27   6.73  Male     No   Sat  Dinner     4           13.94
141       34.30   6.70  Male     No  Thur   Lunch     6           19.53